#!/bin/bash

#############
#TODO: expand privileges functionality
#############



### Checking how many files the user wants to create.
function howMany(){
	
	read quantity;	
	
	if ! [[ "$quantity" =~ ^[0-9]+$ ]]; then
		echo -e "Invalid input!";
		isValid=0;
		#exit;
	elif [ $quantity -gt 10 ]; then
		echo -e "Sorry, i can create 10 files maximum";
		isValid=0;
		#exit;
	elif [ $quantity -eq 0 ]; then
		echo -e "Sorry, i can't create...0 files...";
		isValid=0;		
		#exit;
	else
	isValid=1;
	
	fi

	}


### Determine if we should set higher privileges to the new file.
function privs(){
	read answer;
	case "$answer" in

	[yY])
		chmod 754 $fileName;
		ls -l $fileName;
		understood=1;
		echo -e "Privileges set!";
		;;
	[nN])
		echo -e "Privileges NOT set!";
		understood=1;	
		;;
	*)
		echo -e "I didn't understand...";
		understood=0;
		;;	
	esac;
	}

### Entry point!
echo "Hi, how many files do you want to create [1/10]";
isValid="0";

### While howMany answer is invalid repeat the request.
while [ $isValid == "0" ]
do
	howMany;
done;

### Create $quantity of file asks for the name to assign and privileges
for (( i=1; i<=$quantity; i++ )); do
	echo "Wich name should i assign to file $i?";
	read fileName;
	touch $fileName;
	echo -e "File number '$i' named '$fileName' created! Do you want me to set high privileges (754)? Y/N";
	while [ $understood == "1" ]
	do
		privs;
	done;
done;
### Program ends!
